modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="florianfinn"
description='''Lets the Industrial Foregoing Plant Gatherer harvest mature Croparium crops without removing or replanting them.'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="industrialforegoing"
type="required"
versionRange="[1.21-3.6.38,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cp_lib"
type="required"
versionRange="[5.0.26,)"
ordering="AFTER"
side="BOTH"
